// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI9_7rgGG0ByCEzhJIA1DrwPB4GFdrhQo',
    appId: '1:178650524612:web:53d9228e89941a9ff45291',
    messagingSenderId: '178650524612',
    projectId: 'webrtc-calling-51307',
    authDomain: 'webrtc-calling-51307.firebaseapp.com',
    storageBucket: 'webrtc-calling-51307.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4lzOx-id8FLnrXxjioM5cnZIBgrCon2E',
    appId: '1:178650524612:android:a036dc6bf47faf1bf45291',
    messagingSenderId: '178650524612',
    projectId: 'webrtc-calling-51307',
    storageBucket: 'webrtc-calling-51307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlYqWaxB9Aq-utKYuInbkbweCkVE0oDOo',
    appId: '1:178650524612:ios:ad469afe0c8b9756f45291',
    messagingSenderId: '178650524612',
    projectId: 'webrtc-calling-51307',
    storageBucket: 'webrtc-calling-51307.firebasestorage.app',
    iosBundleId: 'com.example.webrtcCallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlYqWaxB9Aq-utKYuInbkbweCkVE0oDOo',
    appId: '1:178650524612:ios:ad469afe0c8b9756f45291',
    messagingSenderId: '178650524612',
    projectId: 'webrtc-calling-51307',
    storageBucket: 'webrtc-calling-51307.firebasestorage.app',
    iosBundleId: 'com.example.webrtcCallApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI9_7rgGG0ByCEzhJIA1DrwPB4GFdrhQo',
    appId: '1:178650524612:web:4f83dde468151469f45291',
    messagingSenderId: '178650524612',
    projectId: 'webrtc-calling-51307',
    authDomain: 'webrtc-calling-51307.firebaseapp.com',
    storageBucket: 'webrtc-calling-51307.firebasestorage.app',
  );
}
